In [ ]:
import sys
import os
from time import sleep
import numpy as np

def find_change_indices(arr):
    # Konvertiere das Array zu einem numpy-Array
    np_arr = np.array(arr)
    
    # Finde die Indizes, wo sich die Werte ändern
    change_indices = np.where(np.diff(np_arr) != 0)[0] + 1
    
    return change_indices
    
# Füge den Pfad zum Ordner 1 zu sys.path hinzu
sys.path.append("/home/mrt/nas/dropbox/GIT/GitMarkLab/usb_hid_controller")
from class_hid import Controller
controller = Controller() # Name (not nessesary),vid,pid)
controller.init('SNES Controller',"0x0079","0x0126") # USB Clone of SNES Controller
controller.connect()


for i in range(100):
    print(f"Durchlauf {i}")
    

    # get array element of touched button
    result = find_change_indices(controller.get_raw_data()) 
    print(result) 
    # snes controller 0 128 255 
    
    if(True):
        print(
                controller.get_data(304),"  ",
                controller.get_data(305)," ",
                #controller.get_data(3),"  ",
                #controller.get_data(4)," ",
                #controller.get_data(308),"  ",
                #controller.get_data(309)," ",
                #controller.get_data(310)," "
             ) 
    
    #print(controller.get_raw_data())
    sleep(1)




TODO connect
path   /dev/input/event25
controller found init gampad obj:   device /dev/input/event25, name "Controller", phys "usb-0000:00:1d.0-1.2/input0", uniq ""
start thread
Durchlauf 0
[]
-1    -1  
Durchlauf 1
[]
-1    -1  
Durchlauf 2
[304 305]
1    -1  
Durchlauf 3
[304 305]
0    -1  
Durchlauf 4
[304 305]
1    -1  
Durchlauf 5
[304 305]
0    -1  
Durchlauf 6
[304 305]
0    -1  
Durchlauf 7
[304 305]
0    -1  
Durchlauf 8
[304 305]
1    -1  
Durchlauf 9
[304 305]
0    -1  
Durchlauf 10
[304 305]
0    -1  
Durchlauf 11
[304 305]
0    -1  
Durchlauf 12
[304 305]
0    -1  
Durchlauf 13
[304 305 307 308]
0    -1  
Durchlauf 14
[304 305 307 308]
0    -1  
Durchlauf 15
[304 305 307 308]
0    -1  
Durchlauf 16
[304 305 306 307 308]
0    1  
Durchlauf 17
[304 305 306 307 308]
0    1  
Durchlauf 18
[304 306 307 308]
0    0  
Durchlauf 19
[304 308]
0    0  
Durchlauf 20
[304 308]
0    0  
Durchlauf 21
[304 308]
0    0  


In [1]:
from Class_IgusRobolink import IgusRobolink 
import time
    
    
robot = IgusRobolink("192.168.3.11")
robot.connect()
time.sleep(5.0)

Start thread
in Thread
Thread not connected
Connect
Connected to 192.168.3.11 using robolink_dci 
Thread connected


In [2]:
robot.enable()
time.sleep(5.0)

In [2]:
robot.ReferenceAllJoints()

Reference all joints
Reached


In [3]:
status = robot.get_status('MotionStatus')
print(status)
if status == 'MotionNotAllowed':
    print("Reference now ")
    robot.ReferenceAllJoints()
else:
    robot.SetFlag_ReferenceAllJoints(True)
    
    
time.sleep(2)

DOUT
Error in background thread: [Errno 104] Connection reset by peer
Connect
Connected to 192.168.3.11 using robolink_dci 


In [2]:
robot.motion_type("cartesian")

cartesian


In [2]:
import sys
import os
from time import sleep

# Füge den Pfad zum Ordner 1 zu sys.path hinzu
sys.path.append("/home/mrt/nas/dropbox/GIT/GitMarkLab/usb_hid_controller")
from class_hid import Controller
controller = Controller() # Name (not nessesary),vid,pid)
controller.init('SNES Controller',"0x0079","0x0126") # USB Clone of SNES Controller
controller.connect()

TODO connect
path   /dev/input/event25
controller found init gampad obj:   device /dev/input/event25, name "Controller", phys "usb-0000:00:1d.0-1.2/input0", uniq ""
start thread


In [13]:
_z = 10
_xy = 100
while(True):
    if(controller.get_data(308) == 1):
        robot.approach_start('Z',-1*_z)
    if(controller.get_data(309) == 1):
        robot.approach_start('Z',_z)
    if(controller.get_data(0) == 255):
        robot.approach_start('Y',_xy)
    if(controller.get_data(0) == 0):
        robot.approach_start('Y',-1*_xy)
    if(controller.get_data(1) == 255):
        robot.approach_start('X',_xy)
    if(controller.get_data(1) == 0):
        robot.approach_start('X',-1*_xy)    
    if(controller.get_data(304) == 1):
        print("break")
        break 
    else:
        robot.approach_stop()


    

break


In [ ]:
# cartisian coordinate system should be activated while approach, only xyz available actual
robot.approach_start('Z',-5)

In [ ]:
robot.approach_stop()

In [ ]:
robot.approach_start('x',5)

In [ ]:
robot.approach_stop()

In [ ]:
# Run relative transformed position
robot.moveo(200,150,150,0,0,0,100)
robot.get_status('RelativePosition')

In [ ]:
robot.moveo(20,15,16,0,0,0,100)
robot.get_status('RelativePosition')

In [ ]:
# Run absolute Position
x, y, z    =  250.00,0.0, 260.00
rx, ry, rz = -179.99, -00.00, 180.00
speed = 20
robot.move(x,y,z,rx,ry,rz,speed)

In [ ]:
robot.enable_magnet()

In [ ]:
robot.disable_magnet()

In [ ]:
robot.moveo(200,150,150,0,0,0,100)
robot.get_status('GlobalPosition')

In [ ]:
robot.get_status('RelativePosition')

In [ ]:
# touchdown in the corners relative Position
x, y ,z  =  0, 80,19
rx, ry, rz = 0,0,0
s=10

x_max = 290
y_max = 200
y_min = 80
values= [[0,y_min,z],[0,y_max,z],[x_max,y_max,z],[x_max,y_min,z]]

x_values = [0, 50, 100]  # Hier können Sie die gewünschten z-Werte definieren
y_values = [80, 100, 150]  # Hier können Sie die gewünschten z-Werte definieren
z_values = [13]  # Hier können Sie die gewünschten z-Werte definieren


def runrob(x, y, z, rx, ry, rz,s):
    robot.moveo(x, y, z+10, rx, ry, rz,100)
    robot.moveo(x, y, z, rx, ry, rz,s)
    time.sleep(2)
    robot.moveo(x, y, z+10, rx, ry, rz,100)
    return True
    

def move_generator(x, y,z, rx, ry, rz,s):
    #z_values = [200, 250, 180]  # Hier können Sie die gewünschten z-Werte definieren
    for x,y,z in values:
        yield runrob(x, y, z, rx, ry, rz,s)



for result in move_generator(x, y, z,rx, ry, rz,s):
    print(result)

robot.moveo(100,100,50,0,0,0,100)

In [ ]:
robot.disconnect()